import { Assistant, } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';
const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["latin"],
  display : "swap"
});



export const metadata = {
  title: "Create E-commerce Bostrohut app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistant.variable}  antialiased`}
      >
        <Toaster position="top-0 right-0" />
        {children}
      </body>
    </html>
  );
}
