import { Assistant, } from "next/font/google";
import "./globals.css";

const assistant = Assistant({
  variable: "--font-assistant",
  subsets: ["latin"],
  display : "swap"
});



export const metadata = {
  title: "Create E-commerce Bostrohut app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistant.variable}  antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
